# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "134f2a8292d682519fd151e5a277b0d2"
name = "learning-app"
handle = "learning-app-98"
application_url = "https://montana-survivors-sv-interactive.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test1234567148.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://montana-survivors-sv-interactive.trycloudflare.com/auth/callback",
  "https://montana-survivors-sv-interactive.trycloudflare.com/auth/shopify/callback",
  "https://montana-survivors-sv-interactive.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
